### PR TITLE
#28 Removed service container injection

### PR DESCRIPTION
**Pull request by ecourtial**
Related to issue #28 
So after an investigation, they are some major issues, related to DI, in the current version of the ETL.

1. While the ETL is supposed to be usable in any PHP application, it embeds some own DI mechanism (Laravel extension) which may - in some case - trigger incompatibility issues when using custom Extractors/Transformers/Loaders

2. DI injection is done in a dangerous way. We inject the service container (or worst, call it directly)

3. DI is not used when getting the Extractors/Transformers/Loaders. Instead, the developer call it via an alias (as string), then the code uses some binding stuff to call the service container and get the good component.

The PR does the following:
- Remove Illuminate and any Laravel only stuff
- Remove injection of the service container
- Remove the binding. Now, the developer need to inject the component he wants. It is cleaner, follows DI best practices and remove some bloated code.

Side notes:
- The documentation has been cleaned, but might need some improvements. For instance how to integrate it to Laravel, Symfony... For Symfony for instance, it is only 2 lignes of configuration. It also need to be updated with the new way to proceed. If this PR is "pre-approved", I will dot it, and I will also update the changelog.
- This is a major change. We have a BC here, so it would require a new major version.

### CODE REVIEW

**Comment by ecourtial** [comment]
@leomarquine Any feedback?

**Comment by leomarquine** [comment]
I was considering ditch the service container, but in the next major release. Now it is a breaking change.

**Comment by ecourtial** [comment]
Hi @leomarquine 

> I was considering ditch the service container, but in the next major release. Now it is a breaking change.

Then perfect :) . Yes as I said it is a BC. I think it should be nice to do it ASAP. The code is ready, if you "pre-aprove" this PR' I will update the documentation too in the same PR :)

**Comment by ecourtial** [comment]
Hi @leomarquine So what should we do? Is it ok for you so I update the documentation in the same PR?

**Comment by ecourtial** [comment]
Closing. We decided to fork to project and make it evolves in its own way.

**Pull request closed without merging**
