### PR TITLE
Soft delete need the rest of the object to update

### PR DESCRIPTION
**Pull request by dandelionmood**
Hi ! 

Thanks for your work, it's proven quite useful to me !
I just noticed a little bug in the way the soft delete is written, here's my quick and dirty fix !

Pierre

### CODE REVIEW

**Comment by leomarquine** [comment]
But why are you passing all the items to the query? When soft deleting the only column you should update is the `deleted_at` column with the current time.

**Comment by dandelionmood** [comment]
You're right, and that wasn't working either. 
I updated the patch accordingly :) !

**Comment by leomarquine** [comment]
@dandelionmood any news on that?

**Comment by dandelionmood** [comment]
hi @leomarquine the branch « branch-1 » should be OK !

**Comment by leomarquine** [comment]
So we really need this? If you don't set the column it will be bull anyway. Do you have any errors without it?

```php
if( $this->delete === 'soft' ) {
    $item['deleted_at'] = null;
}
```

**Comment by leomarquine** [comment]
@dandelionmood ?

**Comment by dandelionmood** [comment]
Sorry, I didn't have time to check it yet.

Pierre

**Pull request closed without merging**
